services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - ./debug_tools/.env
    environment:
      POSTGRES_DB: indexer
    restart: unless-stopped

  indexer:
    build: .
    ports:
      - "8765:8765"
    env_file:
      - ./debug_tools/.env
    environment:
      DB_HOST: postgres
    volumes:
      - ./plugins:/app/plugins
      - ./config.json:/app/config.json
      - ./repositories.json:/app/repositories.json
    depends_on:
      - postgres
    restart: unless-stopped

