package com.kalynx.centralindexer.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Queries and mutates the {@code comments_index} table.
 *
 * <p>One row per comment thread. {@code comment_id} is the UUID v7 generated by the
 * client at comment creation time — the same identifier used in the git storage path
 * {@code reviews/{reviewId}/comments/{commentId}/}.
 *
 * <p>{@link #findByReviewId} JOINs {@code repositories} to resolve the repository URL
 * for API responses; the surrogate {@code repository_id} does not appear in results.
 */
public final class CommentsIndexRepository {

    private static final String SQL_UPSERT =
            "INSERT INTO " + DbSchema.TABLE_COMMENTS_INDEX +
            " (" + DbSchema.COL_COMMENT_ID + ", " + DbSchema.COL_REVIEW_ID + ", " +
            DbSchema.COL_REPOSITORY_ID + ", " + DbSchema.COL_LAST_UPDATED + ")" +
            " VALUES (?::uuid, ?, ?::uuid, ?)" +
            " ON CONFLICT (" + DbSchema.COL_COMMENT_ID + ") DO UPDATE SET " +
            DbSchema.COL_LAST_UPDATED + " = EXCLUDED." + DbSchema.COL_LAST_UPDATED;

    private static final String SQL_FIND_BY_REVIEW =
            "SELECT ci." + DbSchema.COL_COMMENT_ID + ", r." + DbSchema.COL_URL + " AS repository_url," +
            " ci." + DbSchema.COL_LAST_UPDATED +
            " FROM " + DbSchema.TABLE_COMMENTS_INDEX + " ci" +
            " JOIN " + DbSchema.TABLE_REPOSITORIES + " r ON ci." + DbSchema.COL_REPOSITORY_ID +
            " = r." + DbSchema.COL_REPOSITORY_ID +
            " WHERE ci." + DbSchema.COL_REVIEW_ID + " = ?" +
            " ORDER BY ci." + DbSchema.COL_LAST_UPDATED;

    private final ConnectionPool pool;

    /**
     * Constructs a {@code CommentsIndexRepository} backed by the given connection pool.
     *
     * @param pool the connection pool to use for queries
     */
    public CommentsIndexRepository(ConnectionPool pool) {
        this.pool = pool;
    }

    /**
     * Inserts or updates a comment row. On conflict the {@code last_updated} timestamp
     * is advanced.
     *
     * @param commentId    the UUID v7 comment identifier
     * @param reviewId     the review this comment belongs to
     * @param repositoryId the surrogate UUID of the repository that hosts this comment
     * @param lastUpdated  the timestamp of the triggering event
     * @throws SQLException         if the upsert fails
     * @throws InterruptedException if the thread is interrupted waiting for a connection
     */
    public void upsert(String commentId, String reviewId, String repositoryId, Instant lastUpdated)
            throws SQLException, InterruptedException {
        Connection conn = pool.acquire();
        try (PreparedStatement ps = conn.prepareStatement(SQL_UPSERT)) {
            ps.setString(1, commentId);
            ps.setString(2, reviewId);
            ps.setString(3, repositoryId);
            ps.setTimestamp(4, Timestamp.from(lastUpdated));
            ps.executeUpdate();
        } finally {
            pool.release(conn);
        }
    }

    /**
     * Returns all comment entries for the given review, joined with the repository URL.
     *
     * @param reviewId the review to look up
     * @return ordered list of comment entries; empty if no comments have been indexed yet
     * @throws SQLException         if the query fails
     * @throws InterruptedException if the thread is interrupted waiting for a connection
     */
    public List<CommentEntry> findByReviewId(String reviewId)
            throws SQLException, InterruptedException {
        Connection conn = pool.acquire();
        try (PreparedStatement ps = conn.prepareStatement(SQL_FIND_BY_REVIEW)) {
            ps.setString(1, reviewId);
            try (ResultSet rs = ps.executeQuery()) {
                List<CommentEntry> result = new ArrayList<>();
                while (rs.next()) {
                    Timestamp ts = rs.getTimestamp("last_updated");
                    result.add(new CommentEntry(
                            rs.getString("comment_id"),
                            rs.getString("repository_url"),
                            ts != null ? ts.toInstant() : null));
                }
                return result;
            }
        } finally {
            pool.release(conn);
        }
    }
}
